'''
This module contains functions helpfull with visualisation of results generated by 
neuroevolution. Many of them will be included in reporters however it is also possible to use 
them directly.
'''

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


def plot_statistics(statistics, name, display_window=False,
        file_name=None, csv_file_name=None):
    '''
    This function generates a plot that shows best, avarage and worst fitness in 
    population over all generations.

        @param statistics A statistics reporter object from PyNeat
        @param name Name identifing a specific neuroevolution experiment
        @param display_window If set to true a window with plot will be displayed to user
        @param file_name If not none a plot will be saved into given file
        @param csv_file_name If not none data used for generating plot will be also to written to
                             csv file for future use.
    '''

    generations = range(len(statistics.most_fit_genomes))
    best = [c.fitness for c in statistics.most_fit_genomes]
    avarage = np.array(statistics.get_fitness_mean())

    plt.plot(generations, avarage, '--', label='average')
    plt.plot(generations, best, '-', label='best')

    plt.title('Population fitness')
    plt.xlabel('Generations')
    plt.ylabel('Fitness')
    plt.grid()
    plt.legend()

    if file_name is not None:
        plt.savefig(file_name)
    if display_window is not None:
        plt.show()
    if csv_file_name is not None:
        data_frame = pd.DataFrame({'best': best, 'avarage':avarage})
        data_frame.to_csv(csv_file_name)

    plt.close()

