[package]
name = "bipedal-neuro"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gym = "*"
log = "*"
argparse = "*"
rand = "0.8"
rand_distr = "0.4"
ndarray = "0.13"
ndarray-rand = "0.11"
