[package]
name = "bipedal-neuro"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gym = "*"
rand = "0.7.3"
log = "*"
argparse = "*"
ndarray = "*"
ndarray-rand="*"
